name: Build and Release

on: [push]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "liberica"
          cache: maven
      - name: Build Plugin
        run: mvn -B package --file pom.xml
      - name: Build Theme
        run: mvn -B package --file theme/pom.xml
      - name: Extract Version
        run: |
          echo "RELEASE_VERSION=v$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
      - name: Create Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body: Auto released by GitHub Actions
          prerelease: true
          files: |
            target/*.jar
            theme/target/*.jar
